### ISSUE TITLE
Error: The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by aaronjbaptiste** [juliangruber/capture-phantomjs#5]
I am unable to run the example code (screenshot of https://twitter.com/). I get this error:

```
(node:5928) UnhandledPromiseRejectionWarning: Error: Command failed: 'C:\tools\phantomjs\bin\phantomjs.EXE' '--ignore-ssl-errors=false'   '<local path>\node_modules\capture-phantomjs/script/render.js' 'https://twitter.com/' 1024 768 0 PNG true '[]'
The filename, directory name, or volume label syntax is incorrect.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
(node:5928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5928) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I think it's the shell escape causing the issue, running this seems ok:

`C:\tools\phantomjs\bin\phantomjs.EXE --ignore-ssl-errors=true  --ssl-protocol=sslv3 <local path>\node_modules\capture-phantomjs/script/render.js http://twitter.com/1024 768 0 PNG true []`

node: v8.11.1
npm: 5.6.0
os: Windows 7
phantomjs: 2.1.1
capture-phantomjs: 1.4.2

**Comment by juliangruber** [comment]
Thank you for reporting! I don't have a windows machine to test with, happy to accept PRs!
